apiVersion: apps/v1
kind: Deployment
metadata:
  name: contpost-m2-kc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contpost-m2-kc
  template:
    metadata:
      labels:
        app: contpost-m2-kc
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "dbm2"
        - name: POSTGRES_USER
          value: "dbm2"
        - name: POSTGRES_DB
          value: "dbm2"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: postgres-storage
        emptyDir: {}
