apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: contapa2-m2-kc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: contanode-m2-kc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

