apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: contanode-m2-kc
  name: contanode-m2-kc
spec:
  type: ClusterIP
  ports:
    - name: contanode-m2-kc
      port: 3000
      targetPort: 3000
  externalIPs:
  - 10.0.31.54
  selector:
    io.kompose.service: contanode-m2-kc
status:
  loadBalancer: {}
